<?php

/**
 * This is the model base class for the table "idioma".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Idioma".
 *
 * Columns in table "idioma" available as properties of the model,
 * followed by relations of table "idioma" available as properties of the model.
 *
 * @property string $id
 * @property string $version
 * @property string $idioma_desc
 *
 * @property BusquedaIdioma[] $busquedaIdiomas
 * @property OfertaTrabajoIdioma[] $ofertaTrabajoIdiomas
 */
abstract class BaseIdioma extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'idioma';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Idioma|Idiomas', $n);
	}

	public static function representingColumn() {
		return 'idioma_desc';
	}

	public function rules() {
		return array(
			array('version, idioma_desc', 'required'),
			array('version', 'length', 'max'=>20),
			array('idioma_desc', 'length', 'max'=>255),
			array('id, version, idioma_desc', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'busquedaIdiomas' => array(self::HAS_MANY, 'BusquedaIdioma', 'idioma_id'),
			'ofertaTrabajoIdiomas' => array(self::HAS_MANY, 'OfertaTrabajoIdioma', 'idioma_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'version' => Yii::t('app', 'Version'),
			'idioma_desc' => Yii::t('app', 'Idioma Desc'),
			'busquedaIdiomas' => null,
			'ofertaTrabajoIdiomas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('version', $this->version, true);
		$criteria->compare('idioma_desc', $this->idioma_desc, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}