<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Saturday 10th of May 2014 01:57:19 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		 //"base_url" => "http://www.laburator.com/hybridauth/", 
		"base_url" => "http://www.laburator.com/index.php/user/login/oauth", 

		"providers" => array ( 
			// openid providers
			"LinkedIn" => array ( 
					"enabled" => true,
					"keys"    => array ( "key" => "XXXXXXXXXXXX", "secret" => "XXXXXXXXXXXX" ) 
				),

			/* 
                          "Yahoo" => array ( 
                         
				"enabled" => true,  
				"keys"    => array ( "key" => "XXXXXXXXXXXX", "secret" => "XXXXXXXXXXXX" )
			),
			 */
			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "XXXXXXXXXXXX", "secret" => "XXXXXXXXXXXX" ),
				"scope" => "https://www.googleapis.com/auth/userinfo.profile " . "https://www.googleapis.com/auth/userinfo.email",
                                "access_type" => "online",
			),
                        "Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "XXXXXXXXXXXX", "secret" => "XXXXXXXXXXXX" ), 
			),
/*
			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "BYWNn3erRq63mnM96Bxx9yKyB", "secret" => "lRuGktO1c3sMVH519RjXGeVzei4S1JSwVYvQwBLTjcJSQLcUCP" ) 
			),
 
 */
 
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
